/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dateTimeChecker;

//import tutorial.ResultDialog;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author LapTop
 */
public class DateTimeChecker extends javax.swing.JFrame implements ActionListener{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form DateTimeChecker
     */
    public DateTimeChecker() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultWindow = new javax.swing.JDialog();
        ResultWindow.setName("ResultWindow");
        txtresult = new javax.swing.JLabel();
        txtresult.setName("txtresult");
        btncloseResultWindow = new javax.swing.JButton();
        btncloseResultWindow.setName("btncloseResultWindow");
        btnclear = new javax.swing.JButton();
        btnclear.setName("btnclear");
        btncheck = new javax.swing.JButton();
        btncheck.setName("btncheck");
        lbday = new javax.swing.JLabel();
        lbday.setName("lbday");
        txtyear = new javax.swing.JTextField();
        txtyear.setName("txtyear");
        lbmonth = new javax.swing.JLabel();
        lbmonth.setName("lbmonth");
        txtday = new javax.swing.JTextField();
        txtday.setName("txtday");
        lbyear = new javax.swing.JLabel();
        lbyear.setName("lbyear");
        txtmonth = new javax.swing.JTextField();
        txtmonth.setName("txtmonth");
        lbtitle = new javax.swing.JLabel();
        lbtitle.setName("lbtitle");
        lblogo = new javax.swing.JLabel();
        lblogo.setName("lblogo");

        ResultWindow.setMinimumSize(new java.awt.Dimension(325, 125));

        txtresult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btncloseResultWindow.setText("Close");
        btncloseResultWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseResultWindowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ResultWindowLayout = new javax.swing.GroupLayout(ResultWindow.getContentPane());
        ResultWindow.getContentPane().setLayout(ResultWindowLayout);
        ResultWindowLayout.setHorizontalGroup(
            ResultWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultWindowLayout.createSequentialGroup()
                        .addComponent(btncloseResultWindow)
                        .addGap(8, 8, 8))
                    .addComponent(txtresult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResultWindowLayout.setVerticalGroup(
            ResultWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtresult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncloseResultWindow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResultWindow.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });

        btncheck.setText("Check");
        btncheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncheckMouseClicked(evt);
            }
        });

        lbday.setText("Day");

        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });

        lbmonth.setText("Month");

        lbyear.setText("Year");
        
        lbtitle.setFont(new java.awt.Font("Agency FB", 0, 25)); // NOI18N
        lbtitle.setForeground(new java.awt.Color(0, 153, 255));
        lbtitle.setText("Date Time Checker");

        lblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/Capture.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncheck)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbmonth, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbyear)
                                    .addComponent(lbday, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(84, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmonth))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbyear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclear)
                    .addComponent(btncheck))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    public ResultDialog r = null;
    private void btncheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncheckMouseClicked
        String day = txtday.getText();
        String month = txtmonth.getText();
        String year = txtyear.getText();
        r = new ResultDialog(this, rootPaneCheckingEnabled);
        checkerAlgorithm ca = new checkerAlgorithm();
//        txtresult.setText(ca.checkDate(year, month, day));
//        ResultWindow.setLocationRelativeTo(null);
//        ResultWindow.setVisible(true);
        r.print(ca.checkDate(year, month, day));
        r.setVisible(true);
    }//GEN-LAST:event_btncheckMouseClicked

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
//        txtday.setText("");
//        txtmonth.setText("");
//        txtyear.setText("");
    }//GEN-LAST:event_btnclearMouseClickedTestHelper
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Are you sure to exit?", "Confirm", 
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btncloseResultWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseResultWindowMouseClicked
        // TODO add your handling code here:
        ResultWindow.dispose();
    }//GEN-LAST:event_btncloseResultWindowMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateTimeChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateTimeChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateTimeChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateTimeChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DateTimeChecker d = new DateTimeChecker();  
                d.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);                
                d.setVisible(true);
                d.setBackground(Color.getHSBColor(200,50,100));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ResultWindow;
    private javax.swing.JButton btncheck;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncloseResultWindow;
    private javax.swing.JLabel lbday;
    private javax.swing.JLabel lblogo;
    private javax.swing.JLabel lbmonth;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JLabel lbyear;
    private javax.swing.JTextField txtday;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JLabel txtresult;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
